# Generated by Django 5.1.6 on 2025-02-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofia_blog', '0004_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.DateField(),
        ),
    ]
